version: "3.9"
services:
  client:
    build: client
    container_name: client
    tty: true
    restart: always
    network_mode: host
    volumes:
      - ./client/src:/app/src
      - ./client/source/PythonAPI/carla:/app/PythonAPI
  server:
    build: server
    network_mode: host
    container_name: server
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
