version: "3.9"
services:
  client:
    build: client
    volumes:
      - ./client/src:/app
    networks:
      - carla
  server:
    build: server
    networks:
      - carla
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


networks:
  carla:
    
    
