version: "3.9"
services:
  client:
    build: client
    tty: true
    restart: always
    entrypoint: sh
    network_mode: host
    volumes:
      - ./client/src:/app/src
      - ./client/source/PythonAPI/carla:/app/PythonAPI
  robot:
    build: robot
    tty: true
    restart: always
    entrypoint: sh
    network_mode: host
    volumes:
      - ./robot/src:/app/src
      - ./robot/source/:/app/source
  server:
    build: server
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
