version: "3.9"
services:
  client:
    build: client
    tty: true
    network_mode: host
    volumes:
      - ./client/src:/app
      - vscode-server:/root/..vscode-server
  server:
    build: server
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - 1234:2000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always

volumes:
  vscode-server:
    
